In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
#matplotlib.inline

In [2]:
data=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/train.csv")
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [4]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [5]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [7]:
data.drop(['PoolQC','Fence','MiscFeature','Alley','LotFrontage'],axis=1)

,Id,MSSubClass,MSZoning,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,LandSlope,...,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,8450,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2008,WD,Normal,208500
1,2,20,RL,9600,Pave,Reg,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,5,2007,WD,Normal,181500
2,3,60,RL,11250,Pave,IR1,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,9,2008,WD,Normal,223500
3,4,70,RL,9550,Pave,IR1,Lvl,AllPub,Corner,Gtl,...,272,0,0,0,0,2,2006,WD,Abnorml,140000
4,5,60,RL,14260,Pave,IR1,Lvl,AllPub,FR2,Gtl,...,0,0,0,0,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,7917,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,8,2007,WD,Normal,175000
1456,1457,20,RL,13175,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,2,2010,WD,Normal,210000
1457,1458,70,RL,9042,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,9717,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,112,0,0,0,0,4,2010,WD,Normal,142125
1459,1460,20,RL,9937,Pave,Reg,Lvl,AllPub,Inside,Gtl,...,0,0,0,0,0,6,2008,WD,Normal,147500

In [8]:
data.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [9]:
data1=data[['MSSubClass','LotShape','HouseStyle','OverallQual','OverallCond','RoofStyle','Foundation','TotalBsmtSF','1stFlrSF','2ndFlrSF','GarageArea','PoolArea','SaleType']]

In [10]:
data1

,MSSubClass,LotShape,HouseStyle,OverallQual,OverallCond,RoofStyle,Foundation,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,PoolArea,SaleType
0,60,Reg,2Story,7,5,Gable,PConc,856,856,854,548,0,WD
1,20,Reg,1Story,6,8,Gable,CBlock,1262,1262,0,460,0,WD
2,60,IR1,2Story,7,5,Gable,PConc,920,920,866,608,0,WD
3,70,IR1,2Story,7,5,Gable,BrkTil,756,961,756,642,0,WD
4,60,IR1,2Story,8,5,Gable,PConc,1145,1145,1053,836,0,WD
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,Reg,2Story,6,5,Gable,PConc,953,953,694,460,0,WD
1456,20,Reg,1Story,6,6,Gable,CBlock,1542,2073,0,500,0,WD
1457,70,Reg,2Story,7,9,Gable,Stone,1152,1188,1152,252,0,WD
1458,20,Reg,1Story,5,6,Hip,CBlock,1078,1078,0,240,0,WD
1459,20,Reg,1Story,5,6,Gable,CBlock,1256,1256,0,276,0,WD

In [11]:
numeric_data = data1.select_dtypes(include=[np.number])

In [12]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   OverallQual  1460 non-null   int64
 2   OverallCond  1460 non-null   int64
 3   TotalBsmtSF  1460 non-null   int64
 4   1stFlrSF     1460 non-null   int64
 5   2ndFlrSF     1460 non-null   int64
 6   GarageArea   1460 non-null   int64
 7   PoolArea     1460 non-null   int64
dtypes: int64(8)
memory usage: 91.4 KB

In [13]:
numeric_data.skew()

MSSubClass      1.407657
OverallQual     0.216944
OverallCond     0.693067
TotalBsmtSF     1.524255
1stFlrSF        1.376757
2ndFlrSF        0.813030
GarageArea      0.179981
PoolArea       14.828374
dtype: float64

In [14]:
categorical_data = data1.select_dtypes(exclude=[np.number])

In [15]:
categorical_data

     LotShape HouseStyle RoofStyle Foundation SaleType
0         Reg     2Story     Gable      PConc       WD
1         Reg     1Story     Gable     CBlock       WD
2         IR1     2Story     Gable      PConc       WD
3         IR1     2Story     Gable     BrkTil       WD
4         IR1     2Story     Gable      PConc       WD
...       ...        ...       ...        ...      ...
1455      Reg     2Story     Gable      PConc       WD
1456      Reg     1Story     Gable     CBlock       WD
1457      Reg     2Story     Gable      Stone       WD
1458      Reg     1Story       Hip     CBlock       WD
1459      Reg     1Story     Gable     CBlock       WD

[1460 rows x 5 columns]

In [16]:
categorical_data.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      0
dtype: int64

In [17]:
categorical_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LotShape    1460 non-null   object
 1   HouseStyle  1460 non-null   object
 2   RoofStyle   1460 non-null   object
 3   Foundation  1460 non-null   object
 4   SaleType    1460 non-null   object
dtypes: object(5)
memory usage: 57.2+ KB

In [18]:
categorical_data['LotShape'] = categorical_data['LotShape'].astype('category')
categorical_data['LotShape'] = categorical_data['LotShape'].cat.codes
categorical_data['LotShape']

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

0       3
1       3
2       0
3       0
4       0
       ..
1455    3
1456    3
1457    3
1458    3
1459    3
Name: LotShape, Length: 1460, dtype: int8

In [19]:
categorical_data['HouseStyle']= categorical_data['HouseStyle'].astype('category')
categorical_data['HouseStyle']= categorical_data['HouseStyle'].cat.codes
categorical_data['HouseStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([5, 2, 0, 1, 6, 7, 4, 3], dtype=int8)

In [20]:
categorical_data['RoofStyle'] = categorical_data['RoofStyle'].astype('category')
categorical_data['RoofStyle']= categorical_data['RoofStyle'].cat.codes
categorical_data['RoofStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([1, 3, 2, 4, 0, 5], dtype=int8)

In [21]:
categorical_data['Foundation'] = categorical_data['Foundation'].astype('category')
categorical_data['Foundation']= categorical_data['Foundation'].cat.codes
categorical_data['Foundation'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([2, 1, 0, 5, 3, 4], dtype=int8)

In [22]:
categorical_data['SaleType'] = categorical_data['SaleType'].astype('category')
categorical_data['SaleType']= categorical_data['SaleType'].cat.codes
categorical_data['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([8, 6, 0, 3, 4, 1, 5, 2, 7], dtype=int8)

In [23]:
categorical_data

      LotShape  HouseStyle  RoofStyle  Foundation  SaleType
0            3           5          1           2         8
1            3           2          1           1         8
2            0           5          1           2         8
3            0           5          1           0         8
4            0           5          1           2         8
...        ...         ...        ...         ...       ...
1455         3           5          1           2         8
1456         3           2          1           1         8
1457         3           5          1           4         8
1458         3           2          3           1         8
1459         3           2          1           1         8

[1460 rows x 5 columns]

In [24]:
numeric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1460 non-null   int64
 1   OverallQual  1460 non-null   int64
 2   OverallCond  1460 non-null   int64
 3   TotalBsmtSF  1460 non-null   int64
 4   1stFlrSF     1460 non-null   int64
 5   2ndFlrSF     1460 non-null   int64
 6   GarageArea   1460 non-null   int64
 7   PoolArea     1460 non-null   int64
dtypes: int64(8)
memory usage: 91.4 KB

In [25]:
train_data=pd.concat([numeric_data,categorical_data],axis=1)

In [26]:
train_data

,MSSubClass,OverallQual,OverallCond,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,PoolArea,LotShape,HouseStyle,RoofStyle,Foundation,SaleType
0,60,7,5,856,856,854,548,0,3,5,1,2,8
1,20,6,8,1262,1262,0,460,0,3,2,1,1,8
2,60,7,5,920,920,866,608,0,0,5,1,2,8
3,70,7,5,756,961,756,642,0,0,5,1,0,8
4,60,8,5,1145,1145,1053,836,0,0,5,1,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,6,5,953,953,694,460,0,3,5,1,2,8
1456,20,6,6,1542,2073,0,500,0,3,2,1,1,8
1457,70,7,9,1152,1188,1152,252,0,3,5,1,4,8
1458,20,5,6,1078,1078,0,240,0,3,2,3,1,8
1459,20,5,6,1256,1256,0,276,0,3,2,1,1,8

In [27]:
train_data.skew()

MSSubClass      1.407657
OverallQual     0.216944
OverallCond     0.693067
TotalBsmtSF     1.524255
1stFlrSF        1.376757
2ndFlrSF        0.813030
GarageArea      0.179981
PoolArea       14.828374
LotShape       -0.610175
HouseStyle      0.306755
RoofStyle       1.473796
Foundation      0.091217
SaleType       -3.868638
dtype: float64

In [28]:
X=train_data

In [29]:
X

,MSSubClass,OverallQual,OverallCond,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,PoolArea,LotShape,HouseStyle,RoofStyle,Foundation,SaleType
0,60,7,5,856,856,854,548,0,3,5,1,2,8
1,20,6,8,1262,1262,0,460,0,3,2,1,1,8
2,60,7,5,920,920,866,608,0,0,5,1,2,8
3,70,7,5,756,961,756,642,0,0,5,1,0,8
4,60,8,5,1145,1145,1053,836,0,0,5,1,2,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,6,5,953,953,694,460,0,3,5,1,2,8
1456,20,6,6,1542,2073,0,500,0,3,2,1,1,8
1457,70,7,9,1152,1188,1152,252,0,3,5,1,4,8
1458,20,5,6,1078,1078,0,240,0,3,2,3,1,8
1459,20,5,6,1256,1256,0,276,0,3,2,1,1,8

In [30]:
y=data.SalePrice

In [31]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [32]:
from sklearn.linear_model import LinearRegression
regressor=LinearRegression()
regressor.fit(x_train,y_train)

LinearRegression()

In [33]:
y_pred=regressor.predict(x_test)

In [34]:
y_pred

array([214348.10797571, 110342.12366108, 135043.05305775, 275628.91065506,
       175724.96606283, 116407.76302114, 174721.18127399, 102074.5940915 ,
       224928.14836392, 217539.0836055 , 241671.29921025,  93635.02615047,
       130411.28675746, 258136.64664241, 154349.40053905, 206204.62971094,
       185476.74942041, 125653.9351502 , 203574.20203636, 168670.54107597,
       168010.81728445,  69404.34313389, 147819.30109344, 125716.32476197,
       122912.58634277, 256777.53120069, 217011.41244328, 121211.41496016,
       220251.9133335 , 124258.79669297, 274301.07464045, 206443.43762567,
       146314.34968528, 148667.94278216, 192072.77625986, 215202.33341932,
       221917.82519344, 119948.96915115, 267529.55650892, 175396.95088719,
       190828.30424615, 218025.87455012, 262751.46682444, 186339.06119908,
       215590.45906991, 163751.23168656, 221628.72470375, 130411.28675746,
       107216.31096496, 131793.54336166, 144807.06544092, 177081.34494604,
       198574.35585701, 203869.551486  , 118967.57674803,  92980.36724817,
       143174.74631341, 193138.99942767, 153975.28255217, 306176.44805372,
       193612.88823216, 182389.31366632, 175750.20431051, 208710.67677767,
       136796.3818399 , 118426.19939752, 288804.90765282, 147368.66632809,
       163947.71571943, 130834.75346495, 238749.39209982, 196805.41722179,
       120586.46203693, 212140.05907784, 189497.64829852, 140811.58904752,
       114807.16980791,  98386.64358213, 170024.55308121, 143191.06946813,
        61332.04373266, 188238.80281323, 173674.79059566,  82425.15829021,
       174299.26934864, 263491.59700717, 103500.31259067, 211753.7910726 ,
       174496.67875334, 133625.01310456, 207102.23162562, 161851.22685174,
       219997.88297191, 156610.0260373 , 129991.32732484, 262967.47591849,
       349371.51104157, 198981.55050661, 194431.33533951, 139601.77907047,
        81508.56005825, 343716.25715759, 231817.88027571, 173006.51515166,
       109342.88227925, 153704.97796902, 188950.61459924, 177456.48832408,
       173194.90104934, 233827.11241336, 168896.00730253, 135896.21140187,
       127830.90385179, 296709.046781  , 175889.33612831, 167592.54708846,
       170674.92693474,  68140.46896959, 164738.34611297, 297071.89457551,
       117280.43921736, 245334.93525776, 138850.57192439, 145375.99815879,
       143087.11293121, 176995.47876781, 208014.56361207, 105335.11108069,
       198907.76602955, 226928.27946314, 194818.05022376, 234398.42368631,
       179976.656269  , 310326.39582894, 159140.75346341, 187108.35265383,
       117790.50002041, 181194.71819746, 133518.18182637, 111752.99546625,
       119587.51231161, 201764.31008901, 157887.60527366, 147357.18096626,
        86413.36438241,  43425.01453671, 146529.59087162, 107947.77384743,
       193891.44591494, 203628.91517926, 119417.4534515 , 114944.79166276,
       118368.55289262, 179356.32501811, 104607.50050381, 224999.13592235,
       101526.65777366, 205841.5548292 , 146901.91528683, 216678.76620968,
       219525.61341565, 232423.46340238, 137680.84643537, 178880.04477555,
       147103.28127322, 227712.41060423, 259100.2250147 , 114760.15013086,
        62873.06385633, 247314.82550107, 188320.73417384, 151319.96841429,
       166063.94649328, 104584.19607878, 178525.97501968, 124964.01856539,
       211946.18159893, 141630.46115046, 216570.32981906, 206284.1491919 ,
        83346.42795948, 278577.54660534, 342932.58207282, 217038.00560947,
       119376.43794218, 244007.2332943 , 143431.39237028, 252019.04528312,
       131502.95112922,  62729.1314986 ,  57648.35671846, 184445.09702349,
       139966.57956973, 207454.36825738, 159296.52274758, 307439.52496166,
        42735.23766691, 111061.85544615, 107201.7407092 , 173670.71420837,
       232392.86277546, 236611.33104189, 196482.92063361, 128043.98060907,
       304294.06681884, 315039.59213571, 109408.37341785, 170673.83229111,
       170388.4380468 , 208561.69465018, 188769.99706728, 246779.09840349,
       190926.3196181 , 160073.42446783,  39364.94464225, 204127.49344908,
       139433.58756697, 116803.3711575 , 128599.40685187, 177428.79868952,
       297067.16855197, 167687.27855564, 385368.58268494, 108415.61101437,
       166187.73390584, 126554.87681373, 158430.33199748, 114585.03417658,
       226469.48138202, 184336.7862948 , 252395.7044228 , 278318.02395053,
       200865.92600223, 202012.42543086, 241614.71777461, 271809.38690429,
       190822.27451903, 305608.6403492 , 158354.36408873, 169435.8188411 ,
       180097.48616193, 186338.23756824, 289027.83961096, 267658.61467178,
       166450.83150052, 139565.05524076, 233846.2938521 , 134456.7616555 ,
       188474.48733868, -17853.68033661, 148736.83662672, 128755.85119207,
       140360.64501819, 136258.87326458, 201210.9424332 , 257296.53416903,
       324527.42788584, 178156.64738634, 379509.41059931, 188582.35701682,
       124443.6345045 , 173009.31663286, 168279.49974392, 187462.16256953,
       119018.76986282, 206129.01067801, 214818.20368113, 153367.8543067 ,
       160433.99514164, 220296.48208614, 208132.70661171, 229509.89133445,
       282954.38793006, 199328.44779955, 241776.89662021, 183611.31242571,
       350917.49774571, 125268.60436167, 216303.00514377, 125412.00805539,
       144392.88299183, 136644.04874371, 223136.67203869, 207222.29909547,
       133792.40952906,  81918.20332553, 143227.14114635, 234812.38092464,
       220557.53259967, 161972.63765998,  83376.75371265, 126858.40103706])

In [35]:

regressor.score(x_test,y_test)

0.7157373525374651

In [36]:
test_data=pd.read_csv("/kaggle/input/house-prices-advanced-regression-techniques/test.csv")

In [37]:
test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [38]:
data1=test_data[['MSSubClass','LotShape','HouseStyle','OverallQual','OverallCond','RoofStyle','Foundation','TotalBsmtSF','1stFlrSF','2ndFlrSF','GarageArea','PoolArea','SaleType']]

In [39]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1459 non-null   int64
 1   LotShape     1459 non-null   object
 2   HouseStyle   1459 non-null   object
 3   OverallQual  1459 non-null   int64
 4   OverallCond  1459 non-null   int64
 5   RoofStyle    1459 non-null   object
 6   Foundation   1459 non-null   object
 7   TotalBsmtSF  1458 non-null   float64
 8   1stFlrSF     1459 non-null   int64
 9   2ndFlrSF     1459 non-null   int64
 10  GarageArea   1458 non-null   float64
 11  PoolArea     1459 non-null   int64
 12  SaleType     1458 non-null   object
dtypes: float64(2), int64(6), object(5)
memory usage: 148.3+ KB

In [40]:
data1.isnull().sum()

MSSubClass     0
LotShape       0
HouseStyle     0
OverallQual    0
OverallCond    0
RoofStyle      0
Foundation     0
TotalBsmtSF    1
1stFlrSF       0
2ndFlrSF       0
GarageArea     1
PoolArea       0
SaleType       1
dtype: int64

In [41]:
numeric_data1 = data1.select_dtypes(include=[np.number])
categorical_data1 = data1.select_dtypes(exclude=[np.number])

In [42]:
numeric_data1

,MSSubClass,OverallQual,OverallCond,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,PoolArea
0,20,5,6,882.0,896,0,730.0,0
1,20,6,6,1329.0,1329,0,312.0,0
2,60,5,5,928.0,928,701,482.0,0
3,60,6,6,926.0,926,678,470.0,0
4,120,8,5,1280.0,1280,0,506.0,0
...,...,...,...,...,...,...,...,...
1454,160,4,7,546.0,546,546,0.0,0
1455,160,4,5,546.0,546,546,286.0,0
1456,20,5,7,1224.0,1224,0,576.0,0
1457,85,5,5,912.0,970,0,0.0,0
1458,60,7,5,996.0,996,1004,650.0,0

In [43]:
numeric_data1.isnull().sum()

MSSubClass     0
OverallQual    0
OverallCond    0
TotalBsmtSF    1
1stFlrSF       0
2ndFlrSF       0
GarageArea     1
PoolArea       0
dtype: int64

In [44]:
numeric_data1['TotalBsmtSF']=numeric_data1['TotalBsmtSF'].fillna(0)
numeric_data1['TotalBsmtSF'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

array([ 882., 1329.,  928.,  926., 1280.,  763., 1168.,  789., 1300.,
       1405.,  483.,  525.,  855.,  836., 1590., 1544., 1698., 1822.,
       2846., 1671., 1370., 1324., 1145.,  384.,  847., 1629., 1595.,
       1218., 1468.,  831.,  816., 1208., 1231., 1390., 1488.,  840.,
        600.,  756.,  530., 1642.,  975., 1492., 1829., 1224.,  715.,
       1232., 1209., 1510.,  533., 1728., 1140.,  782., 1080., 1604.,
       1480., 1143., 1206., 1244.,  832.,  864.,  972.,  988.,  576.,
       1175., 1395.,  709.,  936., 1347.,  827., 1027., 1008.,  678.,
        930.,  346.,  738., 1108.,  765.,  608.,  572.,  835.,  780.,
        528., 1124.,  888.,  662., 1422.,  689., 1212.,  707.,  856.,
       1832., 1319.,  720., 1420.,  660., 1117.,  663., 1172., 1508.,
       1250., 1433.,  946., 1222.,  676.,  870.,  878., 1026.,  876.,
       1978., 1040.,  848.,    0.,  381., 1196.,  744.,  960., 1107.,
        894., 1528., 1032.,  423.,  982., 1191.,  480.,  629., 1594.,
       1049., 1243., 1958., 1336., 1214., 1068., 1430., 1344.,  945.,
        546.,  833., 1216.,  624., 1679., 1152., 1434., 2208., 1418.,
       1587.,  952., 1181., 1122., 1427., 1043., 1058., 1621., 1116.,
       1176., 1180.,  804., 1057., 1776., 1365., 2020., 2630., 1736.,
       1782., 1739., 1504., 1774., 1760., 2452., 1082., 1598., 1358.,
       1306., 1350., 2492., 2200., 1884., 1451., 1712.,  728.,  745.,
       1220.,  868.,  846.,  698.,  794., 1177., 1455., 2024., 1070.,
       1173., 1696., 1614., 1702., 2458., 1436., 1402., 1530., 1372.,
        900., 1836., 1652., 1553.,  812., 1141., 1158., 1512., 1114.,
       1450.,  913., 1332.,  754.,  980., 1024.,  912., 2014., 1376.,
       1726.,  691., 1694., 1740.,  392.,  752.,  932., 1288.,  908.,
       1568., 1165., 1048., 1313., 1292., 1680., 1453., 1562., 1169.,
       1202., 1382., 1200., 1866., 1062.,  631.,  793., 1031.,  699.,
        792.,  405., 1054.,  560.,  416.,  630., 1248., 1380.,  951.,
       1105.,  160.,  795., 1041.,  732.,  941., 1045.,  901.,  240.,
        504.,  690.,  801.,  768.,  861.,  677.,  917.,  741.,  245.,
       1022.,  297.,  468., 1072.,  672., 1020., 1204.,  858.,  585.,
       1052.,  456.,  552., 1138.,  825., 1073.,  747., 1089.,  520.,
       1079., 1094., 1555., 1720., 1838., 1282., 1254., 1498.,  704.,
       1449.,  990., 1463., 1431.,  907.,  914., 1569.,  944., 1462.,
       1417., 1578., 1014.,  547., 1078., 1678., 1150.,  583., 1273.,
        920., 1112., 1561., 1067., 1310.,  516.,  561., 1803.,  760.,
       1596.,  902.,  957., 1582., 2190., 1641.,  712., 1645., 1188.,
        796.,  828.,  784.,  680.,  916., 1348., 1664., 1337., 1632.,
       1710., 1675., 1260., 2048., 1211., 1444., 1236.,  896., 1055.,
       2418., 1950., 1850., 1620., 1414.,  948., 1148., 2535., 1603.,
       1479., 1765., 1858., 1367., 1800., 1342.,  764., 1415., 1393.,
       1146., 1037., 1519., 1982., 1064., 1242., 1341.,  955., 1460.,
       1363., 1660., 1162.,  886.,  984.,  890., 1001., 1848., 1235.,
       1419., 1557.,  970., 1230.,  994., 1426., 1625., 1118.,  348.,
       1296., 1036., 1104.,  998., 1824.,  892., 1312., 1081., 1256.,
        854.,  192.,  931.,  884.,  481.,  684.,  904.,  407.,  448.,
        797.,  973.,  723.,  869.,  554.,  981.,  949.,  739.,  992.,
        565.,  989., 1100.,  810., 1272.,  880.,  451.,  536., 1046.,
        450., 1060., 1524.,  570., 1580., 1509.,  621., 1077., 1602.,
        628., 1615., 2271., 1751., 1401., 1182., 1076., 1257., 1357.,
       1778., 1129.,  850., 1445., 1564., 1351., 1092., 1127., 1029.,
        911., 1228.,  644.,  798.,  942., 1091., 1898., 1151.,  173.,
        356.,  592., 1840.,  910., 1277., 1518.,  352., 1495., 1432.,
       1666., 1964., 1189.,  550.,  526.,  462., 1113.,  845.,  686.,
        923.,  938.,  903., 1302., 1166., 1149., 2660., 1612., 2220.,
       1742., 1284.,  725., 1529., 1153., 1259., 1084.,  925., 1061.,
       1790., 2108., 1934., 1994., 2552., 1704., 2320.,  918., 1802.,
       1706., 1317.,  895., 1721., 1298., 1362., 1554., 1577., 1326.,
       1246., 1406., 1266.,  915., 1779., 1408., 1389., 1066., 1325.,
       1369., 1542., 1966., 1538., 1494., 1338., 1335., 1574., 1685.,
       1461., 1223., 1044., 1378., 1511., 1352., 1550., 1339., 2002.,
       2461., 1295., 1093.,  964., 1174., 1042., 1130., 1592.,  822.,
        666.,  370.,  808., 1560., 1053., 1144., 1331.,  922., 1190.,
        924.,  736., 1170., 1377.,  967., 1075.,  616.,  687.,  819.,
        966.,  750.,  969.,  976.,  771., 1005.,  943., 1240.,  671.,
        409.,  484., 1038.,  779., 1643., 2140., 1546., 1489., 1270.,
        879.,  929.,  635., 1097.,  853.,  985., 1015.,  995.,  385.,
       1673.,  979.,  860., 1556., 1531., 1330., 1088., 1179.,  734.,
       5095., 1195., 1290.,  651.,  531.,  851., 1004.,  279.,  859.,
        837., 1573., 1441., 1409., 1454.,  852., 1501., 1689., 1265.,
       1267., 1922., 1491., 1160.,  716., 1396., 1090., 1178., 1617.,
       1705., 1851.,  813.,  781.,  821., 1074., 1700., 2062., 1398.,
       1714., 1910., 1047.,  675., 1103., 1487.,  494., 1069., 1738.,
       1618., 1868., 1606., 1792., 1780., 1686., 1368., 1142., 1035.,
       1540., 1733., 1286., 1670., 1278., 2036., 1400., 1131.,  891.,
       1217.,  636., 1748., 1334.,  569., 1051., 1187., 1251., 1056.,
       1584., 1121., 1050.,  216.,  301., 2171.,  713., 1083., 1135.,
       1438., 1025., 1147.,  502.,  844.,  492.,  770., 1226.,  596.,
        396.,  610.,  806., 1921.,  830., 1059., 1967., 1949.,  872.,
       1865., 1000.,  430.,  799., 1308., 1570., 1388., 1425.,  842.,
        826., 1065.,  954.,  498.,  755.,  818.,  824.,  817.,  637.,
        697.,  432.,  641., 1128., 1381.,  264.,  996.])

In [45]:
numeric_data1['GarageArea']=numeric_data1['GarageArea'].fillna(0)
numeric_data1['GarageArea'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

array([ 730.,  312.,  482.,  470.,  506.,  440.,  420.,  393.,  525.,
        511.,  264.,  320.,  308.,  751.,  868.,  678.,  958.,  756.,
        484.,  430.,  437.,  400.,  433.,  962.,  880.,  676.,  528.,
        429.,  461.,  762.,  713.,  588.,  480.,  496.,  852.,  592.,
        596.,  535.,  660.,  441.,  490.,  504.,  517.,    0.,  315.,
        576.,  620.,  263.,  318.,  305.,  280.,  240.,  551.,  780.,
        288.,  624.,  363.,  200.,  572.,  180.,  365.,  231.,  450.,
        416.,  591.,  690.,  522.,  467.,  209.,  366., 1017.,  615.,
        580.,  513.,  850.,  621.,  319.,  336.,  352.,  260.,  399.,
        473.,  598.,  531.,  625.,  330.,  741.,  776.,  520.,  686.,
        253.,  286.,  495.,  616.,  275.,  502.,  632.,  390.,  564.,
        396.,  409.,  567.,  529.,  479.,  581.,  565.,  478.,  477.,
        345.,  656.,  754.,  864.,  896.,  834.,  932.,  640.,  927.,
        700.,  583.,  886.,  871.,  949.,  685.,  649.,  539.,  701.,
        392.,  397.,  436.,  434.,  644.,  394.,  658.,  410.,  810.,
        815.,  647.,  623.,  972.,  726.,  844.,  492.,  795.,  984.,
        692.,  782.,  711.,  628.,  845.,  788.,  559.,  542.,  465.,
        612.,  732.,  300.,  252.,  524.,  704.,  561.,  641.,  642.,
        540.,  527.,  784.,  515.,  498.,  768.,  610.,  549.,  368.,
        550.,  530.,  297.,  304.,  350.,  294.,  230.,  246.,  720.,
        281.,  907.,  364.,  384.,  900.,  483.,  162.,  324.,  472.,
        287.,  357.,  207.,  216.,  250., 1184.,  316.,  379.,  220.,
        226.,  668.,  340.,  266.,  462.,  672.,  820., 1138.,  846.,
        904.,  662.,  577.,  608.,  343.,  444., 1231.,  570.,  521.,
        523.,  544.,  195.,  313.,  256.,  215.,  307.,  463.,  295.,
        452.,  501.,  351.,  541.,  885.,  578.,  486.,  920.,  698.,
        898.,  386.,  404.,  460.,  683.,  670.,  557.,  738.,  489.,
       1314.,  787.,  905.,  650.,  706., 1150., 1003.,  789.,  746.,
        870.,  944.,  474.,  428.,  431.,  403.,  516.,  687.,  938.,
        783.,  851.,  627.,  276.,  636.,  545.,  546.,  469.,  512.,
        464.,  267.,  451.,  292.,  301., 1488.,  372.,  401.,  311.,
        299.,  225.,  828.,  869.,  342.,  370.,  160.,  355.,  164.,
        360.,  228.,  270.,  626.,  912.,  249.,  322.,  614.,  534.,
        453., 1348.,  874.,  811.,  438.,  558.,  600.,  532.,  725.,
        715.,  560.,  721.,  814.,  205.,  369.,  599.,  344.,  786.,
        356.,  487.,  185.,  816.,  432.,  666.,  435.,  892.,  499.,
        257.,  398.,  729., 1110.,  556.,  724.,  663.,  481.,  585.,
        488.,  856., 1040.,  878., 1174.,  728.,  843.,  916.,  818.,
        774.,  554.,  876.,  631.,  454.,  388.,  630.,  442.,  925.,
        806.,  758.,  933.,  605., 1092.,  574.,  859.,  575.,  590.,
        594.,  744.,  566.,  283.,  476.,  466.,  552., 1105.,  412.,
        510.,  792.,  310.,  293.,  371., 1200.,  338.,  184.,  374.,
        468.,  331.,  224.,  217.,  408.,  456.,  323.,  638.,  494.,
        303.,  332.,  894.,  796.,  674.,  619.,  747.,  497.,  242.,
        597.,  748.,  622.,  579., 1154.,  509.,  691.,  100.,  471.,
        571., 1041.,  963.,  423.,  443.,  773.,  618.,  402.,  675.,
        736.,  722.,  582.,  485.,  543.,  831., 1085.,  899.,  427.,
        617.,  959.,  803.,  760.,  928.,  584.,  449.,  688.,  888.,
        326.,  568.,  273.,  234.,  353.,  684.,  791., 1008.,  648.,
        418.,  378.,  258.,  210.,  586.,  836.,  569.,  848.,  317.,
        646.,  555.,  380.,  265.,  609.,  272.,  518.,  714.,  682.])

In [46]:
numeric_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1459 non-null   int64
 1   OverallQual  1459 non-null   int64
 2   OverallCond  1459 non-null   int64
 3   TotalBsmtSF  1459 non-null   float64
 4   1stFlrSF     1459 non-null   int64
 5   2ndFlrSF     1459 non-null   int64
 6   GarageArea   1459 non-null   float64
 7   PoolArea     1459 non-null   int64
dtypes: float64(2), int64(6)
memory usage: 91.3 KB

In [47]:
categorical_data1

     LotShape HouseStyle RoofStyle Foundation SaleType
0         Reg     1Story     Gable     CBlock       WD
1         IR1     1Story       Hip     CBlock       WD
2         IR1     2Story     Gable      PConc       WD
3         IR1     2Story     Gable      PConc       WD
4         IR1     1Story     Gable      PConc       WD
...       ...        ...       ...        ...      ...
1454      Reg     2Story     Gable     CBlock       WD
1455      Reg     2Story     Gable     CBlock       WD
1456      Reg     1Story     Gable     CBlock       WD
1457      Reg     SFoyer     Gable      PConc       WD
1458      Reg     2Story     Gable      PConc       WD

[1459 rows x 5 columns]

In [48]:
categorical_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   LotShape    1459 non-null   object
 1   HouseStyle  1459 non-null   object
 2   RoofStyle   1459 non-null   object
 3   Foundation  1459 non-null   object
 4   SaleType    1458 non-null   object
dtypes: object(5)
memory usage: 57.1+ KB

In [49]:
categorical_data1.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      1
dtype: int64

In [50]:
categorical_data1['SaleType'].unique()

array(['WD', 'COD', 'New', 'ConLD', 'Oth', 'Con', 'ConLw', 'ConLI', 'CWD',
       nan], dtype=object)

In [51]:
categorical_data1['SaleType']=categorical_data1['SaleType'].fillna('COD')
categorical_data1['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

array(['WD', 'COD', 'New', 'ConLD', 'Oth', 'Con', 'ConLw', 'ConLI', 'CWD'],
      dtype=object)

In [52]:
categorical_data1.isnull().sum()

LotShape      0
HouseStyle    0
RoofStyle     0
Foundation    0
SaleType      0
dtype: int64

In [53]:
categorical_data1['SaleType'] = categorical_data1['SaleType'].astype('category')
categorical_data1['SaleType']= categorical_data1['SaleType'].cat.codes
categorical_data1['SaleType'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([8, 0, 6, 3, 7, 2, 5, 4, 1], dtype=int8)

In [54]:
categorical_data1['Foundation'] = categorical_data1['Foundation'].astype('category')
categorical_data1['Foundation']= categorical_data1['Foundation'].cat.codes
categorical_data1['Foundation'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([1, 2, 0, 4, 3, 5], dtype=int8)

In [55]:
categorical_data1['RoofStyle'] = categorical_data1['RoofStyle'].astype('category')
categorical_data1['RoofStyle']= categorical_data1['RoofStyle'].cat.codes
categorical_data1['RoofStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([1, 3, 2, 0, 4, 5], dtype=int8)

In [56]:
categorical_data1['HouseStyle']= categorical_data1['HouseStyle'].astype('category')
categorical_data1['HouseStyle']= categorical_data1['HouseStyle'].cat.codes
categorical_data1['HouseStyle'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([2, 4, 6, 0, 5, 3, 1], dtype=int8)

In [57]:
categorical_data1['LotShape'] = categorical_data1['LotShape'].astype('category')
categorical_data1['LotShape'] = categorical_data1['LotShape'].cat.codes
categorical_data1['LotShape'].unique()

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

array([3, 0, 1, 2], dtype=int8)

In [58]:
test_data1=pd.concat([numeric_data1,categorical_data1],axis=1)

In [59]:
test_data1.head()

,MSSubClass,OverallQual,OverallCond,TotalBsmtSF,1stFlrSF,2ndFlrSF,GarageArea,PoolArea,LotShape,HouseStyle,RoofStyle,Foundation,SaleType
0,20,5,6,882.0,896,0,730.0,0,3,2,1,1,8
1,20,6,6,1329.0,1329,0,312.0,0,0,2,3,1,8
2,60,5,5,928.0,928,701,482.0,0,0,4,1,2,8
3,60,6,6,926.0,926,678,470.0,0,0,4,1,2,8
4,120,8,5,1280.0,1280,0,506.0,0,0,2,1,2,8

In [60]:
test=regressor.predict(test_data1)

In [61]:
test

array([134630.86308986, 179883.25287566, 166605.49224374, ...,
       153805.08764417, 100832.70030886, 231580.22664813])

In [62]:
sub=pd.DataFrame({"Id":test_data.Id,"SalePrice":test})

In [63]:
sub

        Id      SalePrice
0     1461  134630.863090
1     1462  179883.252876
2     1463  166605.492244
3     1464  191900.722373
4     1465  218283.155988
...    ...            ...
1454  2915   61339.678059
1455  2916   67816.046354
1456  2917  153805.087644
1457  2918  100832.700309
1458  2919  231580.226648

[1459 rows x 2 columns]

In [64]:
sub.to_csv('submission.csv',index=False)